### ISSUE TITLE
Any progress on repo and/or sub-module development?

### ISSUE THREAD

**Issue by justingreenberg** [mateodelnorte/microsvc-example#1]
I really think you nailed the essence of production node microservices with these libraries, I'm wondering if there were any updates you could push up, ie some of the todos such as event sourcing using `sourced` & `sourced-repo-mongo` and `servicebus` plugin/middleware integration? 

Thanks again for the great work :+1:

**Comment by mateodelnorte** [comment]
Thanks, @justingreenberg. Sorry for the late reply. Just got back from a 2 week vacation, sailing around the Croatian coast. :D 

Appreciate the praise. I'm going to be investing more time into making all of these projects tighter and more useful. 

I'd love your help, if you'd like to lend it.
